version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: docc_stock
      POSTGRES_USER: docc_user
      POSTGRES_PASSWORD: docc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://docc_user:docc_password@postgres:5432/docc_stock
      JWT_SECRET: docc_jwt_secret_key_2024
      NODE_ENV: production
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5001
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data: